_target_: src.model_module.dcd_music_lightning.DCDMusicLightning
tau: 8
diff_method:
  - esprit
  - music_1D
train_loss_type:
  - rmspe
  - rmspe
field_type: Near
regularization: null
variant: small
norm_layer: false
state_path: null
learning_rate: ${training.learning_rate}
weight_decay: ${training.weight_decay}
optimizer: ${training.optimizer}
scheduler: ${training.scheduler}
step_size: ${training.step_size}
gamma: ${training.gamma}
momentum: 0.9
