defaults:
  - default
  - system_model: default
  - dataset: default
  - training: default
  - simulation: default
  - data: default
  - model: subspacenet
  - trainer: default
  - callbacks: default
  - runtime: default
  - _self_

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
